platform :ios, '12.0'

target 'WeMapSDK_Example' do
  use_frameworks!

  # 의존성 추가
  pod 'Mapbox-iOS-SDK', '~> 5.6.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
