platform :ios, '12.0'

target 'WeMapSDK_Example' do
  use_frameworks!

  # WeMapSDK 로컬 경로 참조
  pod 'WeMapSDK', :path => '../'

  # MapboxMaps 의존성 추가
  pod 'MapboxMaps', '11.8.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 모든 타겟의 최소 Deployment Target 설정
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
